Create MailPiece.dart
umgc/fall2022 pull request #488
Opened 2022-09-27 02:47 UTC by shiftClick

sample commit, test

2022-09-27 04:11 UTC, umgcjack requested changes

2022-09-27 04:11 UTC, umgcjack commented on lib/models/MailPiece.dart
> +  AddressObject _senderAddress;
These all need to be public (not prefixed with `_`).

2022-09-27 04:11 UTC, umgcjack commented on lib/models/MailPiece.dart
> +
You could probably remove these, and it wouldn't hurt to end the file in a newline.

2022-09-27 04:14 UTC, umgcjack requested changes

2022-09-27 04:14 UTC, umgcjack commented on lib/models/MailPiece.dart
> +  AddressObject _senderAddress;
I'd make this a `String`. Otherwise, you'll need to import whatever library provides this type.

2022-09-27 13:06 UTC, mdconatser commented
It looks like a MailPiece class was already added (mistakenly to the root directory of the project). Recommend just moving that file into lib/models.

2022-09-27 13:07 UTC, mdconatser requested changes
It looks like a MailPiece class was already added (mistakenly to the root directory of the project). It looks like Shane's current PR moves this file to this location already, so recommend just abandoning this pr

2022-09-28 13:01 UTC, closed without merging

2022-09-28 13:01 UTC, shaneknows commented
PR is OBE