Adjusted mail view semantics
umgc/fall2022 pull request #618
Opened 2022-10-16 14:49 UTC by tatikozh

Added buttons to dialogs to allow handling them with voice controls Added conditions to avoid errors during login
Added UI elements to top and bottom bars
The navigation stack is clear when the user navigates to the home or login page, which prevents using the back gesture to go to the previous page

2022-10-17 00:56 UTC, mdconatser approved these changes, later dismissed

2022-10-18 13:54 UTC, shaneknows requested changes
Please merge with dev and resolve conflicts. I tried to locally, but it seemed too complicated

2022-10-18 18:59 UTC, shaneknows approved these changes
Love it

2022-10-19 16:38 UTC, cthorn2 approved these changes
Well done!

2022-10-19 16:39 UTC, merged