Fahimi/google assistant
umgc/fall2022 pull request #619
Opened 2022-10-16 22:38 UTC by AliFahimi

This fixes a couple bugs with my last PR, as well as makes it so we operate correctly when the application is started by an intent (if the app was closed).

Bug Fixes:
When we got an intent, all pages in the stack would attempt to navigate.
Sending an intent on the sign in page does nothing. It now will pop up a dialog.

Features:
We will now process intents that are sent when the application is starting.
Starting work for adding notifications.

2022-10-17 00:56 UTC, mdconatser approved these changes

2022-10-18 13:20 UTC, mdconatser submitted a review, later dismissed

2022-10-18 15:12 UTC, shaneknows requested changes
Please merge with origin/developer and resolve conflicts

2022-10-18 23:01 UTC, AliFahimi commented
Conflicts have been resolved

2022-10-20 12:26 UTC, mdconatser submitted a review, later dismissed

2022-10-20 16:16 UTC, shaneknows approved these changes

2022-10-21 01:27 UTC, lwvantassel approved these changes

2022-10-21 01:35 UTC, merged