Origin/bug/663
umgc/fall2022 pull request #742
Opened 2022-10-31 20:48 UTC by ntafese

2022-10-31 22:48 UTC, mdconatser requested changes

2022-10-31 22:48 UTC, mdconatser commented on lib/services/mail_notifier.dart
> +    var test = db.query(MAIL_PIECE_TABLE);
remove test query and resulting output

2022-10-31 22:48 UTC, mdconatser commented
also run unit tests and resolve

2022-11-01 22:54 UTC, ntafese commented on lib/services/mail_notifier.dart
> +    var test = db.query(MAIL_PIECE_TABLE);
removed

2022-11-02 12:41 UTC, mdconatser approved these changes

2022-11-02 13:59 UTC, shaneknows approved these changes

2022-11-02 13:59 UTC, merged